name: Build Swift
on: [workflow_dispatch]
jobs:

    build-swift-armv7:
        name: Build Swift
        runs-on: ubuntu-latest
        container: orobio/swift-armv7-build:5.10
        timeout-minutes: 480
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Swift Version
          run: swift --version
        - name: Build
          run: |
            export SWIFT_NATIVE_PATH=/opt/swift/5.10/usr/bin
            export SRC_ROOT=$GITHUB_WORKSPACE
            ./build.sh
        - name: Archive Swift Build artifacts
          uses: actions/upload-artifact@v3
          with:
            name: swift-armv7
            path: ./workspace/build/swift-armv7.tar.gz
